My first commit

diff --git a/0x00-shell_basics/6-firstdirectory b/0x00-shell_basics/6-firstdirectory
--- a/0x00-shell_basics/6-firstdirectory
+++ b/0x00-shell_basics/6-firstdirectory
@@ -1,2 +1,12 @@
 #!/bin/bash
-mkdir /tmp/my_first_directory: directory
+mkdir /tmp/my_first_directory
+
+if [ $? -eq 0 ]; then
+
+	  echo "Directory created successfully!"
+
+  else
+
+	    echo "Directory creation failed."
+
+fi
